#!/bin/sh
# Placeholder — the real gradlew wrapper executable is generated by Android Studio
# or by running:
#   gradle wrapper --gradle-version 8.2
# in the eve-android/ directory.
#
# The wrapper JAR (gradle-wrapper.jar) is a binary and is not stored in this
# repository.  Clone the project into Android Studio and it will generate both
# gradlew and the JAR automatically.
echo "gradlew not bootstrapped. Open this project in Android Studio or run 'gradle wrapper --gradle-version 8.2'."
exit 1
